remote_theme: pages-themes/hacker@v0.2.0
name: bad-hosts
description: A huge hosts file for blocking ads, trackers and malware hosts.
github:
  zip_url: http://example.com/download.zip
  another_url: another value
